# Generated by Django 4.0.7 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_createdat_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
