# Generated by Django 4.0.7 on 2023-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Construção civil', 'Construção civil'), ('Manutenção de Eletrônicos', 'Manutenção de Eletrônicos'), ('Frete', 'Frete'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
    ]
