# Generated by Django 4.1.5 on 2023-01-04 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serviceDescription", models.CharField(max_length=50)),
                ("serviceValue", models.DecimalField(decimal_places=2, max_digits=5)),
                ("atuationArea", models.CharField(max_length=50)),
            ],
        ),
    ]
