# Generated by Django 4.0.7 on 2023-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='service_description',
            field=models.TextField(),
        ),
    ]
