# Generated by Django 4.0.7 on 2023-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
